version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/terraform
  build:
    commands:
      - git clone $REPOSITORY_URL repo
      - cd repo/terraform
      - terraform init -input=false
      - terraform apply -auto-approve -input=false
