version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/terraform
      - apt-get update -y
      - apt-get install -y jq
  build:
    commands:
      - git clone $REPOSITORY_URL repo
      - cd repo/tenant
      - |
          terraform init -input=false \
            -backend-config="bucket=$STATE_BUCKET" \
            -backend-config="key=$TENANT_ID/terraform.tfstate" \
            -backend-config="dynamodb_table=$LOCK_TABLE"
      - |
          if [ "$ACTION" = "destroy" ]; then
            terraform destroy -auto-approve -input=false \
              -var "tenant_id=$TENANT_ID"
          else
            terraform apply -auto-approve -input=false \
              -var "tenant_id=$TENANT_ID" \
              -var "server_type=$SERVER_TYPE" \
              -var "instance_type=$INSTANCE_TYPE" \
              -var "overworld_border_radius=$OVERWORLD_BORDER" \
              -var "nether_border_radius=$NETHER_BORDER"
          fi

