name: Server Terraform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        run: terraform -chdir=tenant fmt -check -recursive
      - name: Terraform init (local backend)
        run: terraform -chdir=tenant init -backend=false
      - name: Terraform validate
        run: terraform -chdir=tenant validate
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Shellcheck user_data
        run: shellcheck tenant/user_data.sh
